sudo: required
language: node_js
node_js:
  - "7"
python:
  - "3.4"
script:
  - echo "Deploy!"
install:
  - npm install -g firebase-tools
  - sudo pip install pyrebase
  - cd functions  &&  npm install
after_success:
  - cd $TRAVIS_BUILD_DIR 
  - python APIcacheConstructor.py
  - firebase deploy --project "njack-web" --token "$FIREBASE_TOKEN"
branches:
  only:
    - firebase-deploy
