language: node_js
node_js:
 — “7”
branches:
 only:
  - firebase-deploy
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project njack-web — token $FIREBASE_TOKEN.
