language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!"
install:
  - npm install -g firebase-tools
  - npm install
after_success:
  - firebase deploy --project "njack-web" --token "$FIREBASE_TOKEN"
branches:
  only:
    - firebase-deploy
